import numpy as np
from spira.yevon.geometry.coord import Coord


DEG2RAD = np.pi / 180.0
RAD2DEG = 180.0 / np.pi

SCALE_UP = 1e+6
SCALE_DOWN = 1e-6
OFFSET = 0.3

PATH_TYPE_NORMAL = 0
PATH_TYPE_ROUNDED = 1
PATH_TYPE_EXTENDED = 2

PATH_TYPES = [
    PATH_TYPE_NORMAL,
    PATH_TYPE_ROUNDED,
    PATH_TYPE_EXTENDED
]

EDGE_TYPE_NORMAL = 0
EDGE_TYPE_INSIDE = 1
EDGE_TYPE_OUTSIDE = 2
EDGE_TYPE_EUCLIDEAN = 3
EDGE_TYPE_SQUARE = 4
EDGE_TYPE_SIDE_EXTEND = 5

EDGE_TYPES = [
    EDGE_TYPE_NORMAL,
    EDGE_TYPE_INSIDE,
    EDGE_TYPE_OUTSIDE,
    EDGE_TYPE_EUCLIDEAN,
    EDGE_TYPE_SQUARE,
    EDGE_TYPE_SIDE_EXTEND
]

CLIPPER_SCALE = 2**30

NORTH = Coord(0.0, 1.0)
SOUTH = Coord(0.0, -1.0)
EAST = Coord(1.0, 0.0)
WEST = Coord(-1.0, 0.0)





